// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter/greetpb/greet.proto

package greetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LongGreetRequest struct {
	MessageLong          string   `protobuf:"bytes,1,opt,name=messageLong,proto3" json:"messageLong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongGreetRequest) Reset()         { *m = LongGreetRequest{} }
func (m *LongGreetRequest) String() string { return proto.CompactTextString(m) }
func (*LongGreetRequest) ProtoMessage()    {}
func (*LongGreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd44c5ec7fcb3850, []int{0}
}

func (m *LongGreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetRequest.Unmarshal(m, b)
}
func (m *LongGreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetRequest.Marshal(b, m, deterministic)
}
func (m *LongGreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetRequest.Merge(m, src)
}
func (m *LongGreetRequest) XXX_Size() int {
	return xxx_messageInfo_LongGreetRequest.Size(m)
}
func (m *LongGreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetRequest proto.InternalMessageInfo

func (m *LongGreetRequest) GetMessageLong() string {
	if m != nil {
		return m.MessageLong
	}
	return ""
}

type LongGreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongGreetResponse) Reset()         { *m = LongGreetResponse{} }
func (m *LongGreetResponse) String() string { return proto.CompactTextString(m) }
func (*LongGreetResponse) ProtoMessage()    {}
func (*LongGreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd44c5ec7fcb3850, []int{1}
}

func (m *LongGreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetResponse.Unmarshal(m, b)
}
func (m *LongGreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetResponse.Marshal(b, m, deterministic)
}
func (m *LongGreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetResponse.Merge(m, src)
}
func (m *LongGreetResponse) XXX_Size() int {
	return xxx_messageInfo_LongGreetResponse.Size(m)
}
func (m *LongGreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetResponse proto.InternalMessageInfo

func (m *LongGreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd44c5ec7fcb3850, []int{2}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GreetRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd44c5ec7fcb3850, []int{3}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetManyTimesRequest struct {
	FirstNames           string   `protobuf:"bytes,1,opt,name=firstNames,proto3" json:"firstNames,omitempty"`
	LastNames            string   `protobuf:"bytes,2,opt,name=lastNames,proto3" json:"lastNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyTimesRequest) Reset()         { *m = GreetManyTimesRequest{} }
func (m *GreetManyTimesRequest) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimesRequest) ProtoMessage()    {}
func (*GreetManyTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd44c5ec7fcb3850, []int{4}
}

func (m *GreetManyTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimesRequest.Unmarshal(m, b)
}
func (m *GreetManyTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimesRequest.Marshal(b, m, deterministic)
}
func (m *GreetManyTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimesRequest.Merge(m, src)
}
func (m *GreetManyTimesRequest) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimesRequest.Size(m)
}
func (m *GreetManyTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimesRequest proto.InternalMessageInfo

func (m *GreetManyTimesRequest) GetFirstNames() string {
	if m != nil {
		return m.FirstNames
	}
	return ""
}

func (m *GreetManyTimesRequest) GetLastNames() string {
	if m != nil {
		return m.LastNames
	}
	return ""
}

type GreetManyTimesResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyTimesResponse) Reset()         { *m = GreetManyTimesResponse{} }
func (m *GreetManyTimesResponse) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimesResponse) ProtoMessage()    {}
func (*GreetManyTimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd44c5ec7fcb3850, []int{5}
}

func (m *GreetManyTimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimesResponse.Unmarshal(m, b)
}
func (m *GreetManyTimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimesResponse.Marshal(b, m, deterministic)
}
func (m *GreetManyTimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimesResponse.Merge(m, src)
}
func (m *GreetManyTimesResponse) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimesResponse.Size(m)
}
func (m *GreetManyTimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimesResponse proto.InternalMessageInfo

func (m *GreetManyTimesResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*LongGreetRequest)(nil), "greet.LongGreetRequest")
	proto.RegisterType((*LongGreetResponse)(nil), "greet.LongGreetResponse")
	proto.RegisterType((*GreetRequest)(nil), "greet.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "greet.GreetResponse")
	proto.RegisterType((*GreetManyTimesRequest)(nil), "greet.GreetManyTimesRequest")
	proto.RegisterType((*GreetManyTimesResponse)(nil), "greet.GreetManyTimesResponse")
}

func init() { proto.RegisterFile("greeter/greetpb/greet.proto", fileDescriptor_bd44c5ec7fcb3850) }

var fileDescriptor_bd44c5ec7fcb3850 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x42, 0x5b, 0x33, 0x2a, 0xd8, 0x55, 0x6b, 0x89, 0x55, 0xca, 0x5e, 0x2c, 0x08, 0xb5,
	0x68, 0x7f, 0x81, 0x1e, 0x14, 0x51, 0x0f, 0x6d, 0xbd, 0x78, 0xdb, 0xc2, 0x18, 0x02, 0xf9, 0x72,
	0x67, 0x2b, 0xf8, 0x73, 0xfd, 0x27, 0x92, 0xcd, 0xa4, 0xdd, 0x46, 0x94, 0x9e, 0x96, 0xf7, 0xde,
	0xbc, 0xf7, 0x36, 0xd9, 0x81, 0xd3, 0x50, 0x23, 0x1a, 0xd4, 0x57, 0xf6, 0xcc, 0xe7, 0xe5, 0x39,
	0xcc, 0x75, 0x66, 0x32, 0xd1, 0xb0, 0x40, 0x8e, 0xe1, 0xe0, 0x29, 0x4b, 0xc3, 0xfb, 0x02, 0x4c,
	0xf0, 0x63, 0x81, 0x64, 0x44, 0x1f, 0x76, 0x13, 0x24, 0x52, 0x21, 0x16, 0x52, 0xd7, 0xeb, 0x7b,
	0x03, 0x7f, 0xe2, 0x52, 0xf2, 0x12, 0xda, 0x8e, 0x8b, 0xf2, 0x2c, 0x25, 0x14, 0x1d, 0x68, 0x6a,
	0xa4, 0x45, 0x6c, 0xd8, 0xc1, 0x48, 0x3e, 0xc0, 0xde, 0x5a, 0x7c, 0x0f, 0xfc, 0xf7, 0x48, 0x93,
	0x79, 0x51, 0x09, 0xf2, 0xe8, 0x8a, 0x10, 0x01, 0xec, 0xc4, 0x8a, 0xc5, 0x6d, 0x2b, 0x2e, 0xb1,
	0xbc, 0x80, 0xfd, 0xcd, 0x2a, 0x5f, 0xe1, 0xd8, 0x0e, 0x3e, 0xab, 0xf4, 0x6b, 0x16, 0x25, 0x48,
	0x55, 0xf7, 0x39, 0xc0, 0xb2, 0x8a, 0xd8, 0xe4, 0x30, 0xc5, 0xdd, 0xaa, 0x36, 0xe2, 0xfa, 0x15,
	0x21, 0x47, 0xd0, 0xa9, 0xc7, 0xfe, 0x7f, 0x91, 0xeb, 0x6f, 0x0f, 0x5a, 0xfc, 0x0a, 0x62, 0x0c,
	0x0d, 0xeb, 0x16, 0x87, 0xc3, 0xf2, 0x21, 0xdc, 0xbf, 0x12, 0x1c, 0xad, 0x93, 0x65, 0xae, 0xdc,
	0x12, 0x33, 0x68, 0x5b, 0x6a, 0x8a, 0xfa, 0x13, 0xf5, 0xd4, 0x68, 0x54, 0x89, 0xe8, 0xb9, 0xc3,
	0xf5, 0x8f, 0x0c, 0xce, 0xfe, 0x50, 0xab, 0xcc, 0x91, 0x27, 0x1e, 0x39, 0xf5, 0x2e, 0x8e, 0x30,
	0x35, 0x9c, 0x7a, 0xc2, 0xbe, 0xfa, 0x42, 0x04, 0xdd, 0xdf, 0x42, 0x95, 0x35, 0xf0, 0x6e, 0xfd,
	0xb7, 0x16, 0x2f, 0xd8, 0xbc, 0x69, 0x77, 0xeb, 0xe6, 0x27, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x66,
	0xa5, 0x87, 0x7a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Unary
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
	GreetServerStream(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (Greeter_GreetServerStreamClient, error)
	GreetClientStream(ctx context.Context, opts ...grpc.CallOption) (Greeter_GreetClientStreamClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/greet.greeter/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GreetServerStream(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (Greeter_GreetServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/greet.greeter/GreetServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterGreetServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_GreetServerStreamClient interface {
	Recv() (*GreetManyTimesResponse, error)
	grpc.ClientStream
}

type greeterGreetServerStreamClient struct {
	grpc.ClientStream
}

func (x *greeterGreetServerStreamClient) Recv() (*GreetManyTimesResponse, error) {
	m := new(GreetManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) GreetClientStream(ctx context.Context, opts ...grpc.CallOption) (Greeter_GreetClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[1], "/greet.greeter/GreetClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterGreetClientStreamClient{stream}
	return x, nil
}

type Greeter_GreetClientStreamClient interface {
	Send(*LongGreetRequest) error
	CloseAndRecv() (*LongGreetResponse, error)
	grpc.ClientStream
}

type greeterGreetClientStreamClient struct {
	grpc.ClientStream
}

func (x *greeterGreetClientStreamClient) Send(m *LongGreetRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterGreetClientStreamClient) CloseAndRecv() (*LongGreetResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongGreetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Unary
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	GreetServerStream(*GreetManyTimesRequest, Greeter_GreetServerStreamServer) error
	GreetClientStream(Greeter_GreetClientStreamServer) error
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) Greet(ctx context.Context, req *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (*UnimplementedGreeterServer) GreetServerStream(req *GreetManyTimesRequest, srv Greeter_GreetServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetServerStream not implemented")
}
func (*UnimplementedGreeterServer) GreetClientStream(srv Greeter_GreetClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetClientStream not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.greeter/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GreetServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).GreetServerStream(m, &greeterGreetServerStreamServer{stream})
}

type Greeter_GreetServerStreamServer interface {
	Send(*GreetManyTimesResponse) error
	grpc.ServerStream
}

type greeterGreetServerStreamServer struct {
	grpc.ServerStream
}

func (x *greeterGreetServerStreamServer) Send(m *GreetManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_GreetClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).GreetClientStream(&greeterGreetClientStreamServer{stream})
}

type Greeter_GreetClientStreamServer interface {
	SendAndClose(*LongGreetResponse) error
	Recv() (*LongGreetRequest, error)
	grpc.ServerStream
}

type greeterGreetClientStreamServer struct {
	grpc.ServerStream
}

func (x *greeterGreetClientStreamServer) SendAndClose(m *LongGreetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterGreetClientStreamServer) Recv() (*LongGreetRequest, error) {
	m := new(LongGreetRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _Greeter_Greet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetServerStream",
			Handler:       _Greeter_GreetServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GreetClientStream",
			Handler:       _Greeter_GreetClientStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "greeter/greetpb/greet.proto",
}
