// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pricing/priceProtos/price.proto

package priceProtos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PriceRequest struct {
	PriceItemA           int32    `protobuf:"varint,1,opt,name=priceItemA,proto3" json:"priceItemA,omitempty"`
	PriceItemB           int32    `protobuf:"varint,2,opt,name=priceItemB,proto3" json:"priceItemB,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceRequest) Reset()         { *m = PriceRequest{} }
func (m *PriceRequest) String() string { return proto.CompactTextString(m) }
func (*PriceRequest) ProtoMessage()    {}
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61dbec4ba1450e28, []int{0}
}

func (m *PriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceRequest.Unmarshal(m, b)
}
func (m *PriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceRequest.Marshal(b, m, deterministic)
}
func (m *PriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceRequest.Merge(m, src)
}
func (m *PriceRequest) XXX_Size() int {
	return xxx_messageInfo_PriceRequest.Size(m)
}
func (m *PriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PriceRequest proto.InternalMessageInfo

func (m *PriceRequest) GetPriceItemA() int32 {
	if m != nil {
		return m.PriceItemA
	}
	return 0
}

func (m *PriceRequest) GetPriceItemB() int32 {
	if m != nil {
		return m.PriceItemB
	}
	return 0
}

type PriceResponse struct {
	TotalPrice           int32    `protobuf:"varint,1,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceResponse) Reset()         { *m = PriceResponse{} }
func (m *PriceResponse) String() string { return proto.CompactTextString(m) }
func (*PriceResponse) ProtoMessage()    {}
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61dbec4ba1450e28, []int{1}
}

func (m *PriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceResponse.Unmarshal(m, b)
}
func (m *PriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceResponse.Marshal(b, m, deterministic)
}
func (m *PriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceResponse.Merge(m, src)
}
func (m *PriceResponse) XXX_Size() int {
	return xxx_messageInfo_PriceResponse.Size(m)
}
func (m *PriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PriceResponse proto.InternalMessageInfo

func (m *PriceResponse) GetTotalPrice() int32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*PriceRequest)(nil), "price.PriceRequest")
	proto.RegisterType((*PriceResponse)(nil), "price.PriceResponse")
}

func init() { proto.RegisterFile("pricing/priceProtos/price.proto", fileDescriptor_61dbec4ba1450e28) }

var fileDescriptor_61dbec4ba1450e28 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0x4c,
	0xce, 0xcc, 0x4b, 0xd7, 0x07, 0xd1, 0xa9, 0x01, 0x45, 0xf9, 0x25, 0xf9, 0xc5, 0x10, 0xb6, 0x5e,
	0x01, 0x88, 0x23, 0xc4, 0x0a, 0xe6, 0x28, 0xf9, 0x71, 0xf1, 0x04, 0x80, 0x18, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x72, 0x5c, 0x5c, 0x60, 0x09, 0xcf, 0x92, 0xd4, 0x5c, 0x47, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x24, 0x11, 0x14, 0x79, 0x27, 0x09, 0x26, 0x34, 0x79, 0x27,
	0x25, 0x7d, 0x2e, 0x5e, 0xa8, 0x79, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x20, 0x0d, 0x25, 0xf9,
	0x25, 0x89, 0x39, 0x60, 0x51, 0x98, 0x81, 0x08, 0x11, 0x23, 0x47, 0x2e, 0x36, 0xb0, 0xf6, 0x22,
	0x21, 0x73, 0x2e, 0x0e, 0xf7, 0xd4, 0x12, 0xb0, 0xa8, 0x90, 0xb0, 0x1e, 0xc4, 0xad, 0xc8, 0x6e,
	0x93, 0x12, 0x41, 0x15, 0x84, 0x58, 0xa0, 0xc4, 0xe0, 0xc4, 0x1b, 0xc5, 0x8d, 0xe4, 0xcb, 0x24,
	0x36, 0xb0, 0x07, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x65, 0x4a, 0x6b, 0x4b, 0x03, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PricerClient is the client API for Pricer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PricerClient interface {
	GetPrice(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error)
}

type pricerClient struct {
	cc *grpc.ClientConn
}

func NewPricerClient(cc *grpc.ClientConn) PricerClient {
	return &pricerClient{cc}
}

func (c *pricerClient) GetPrice(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error) {
	out := new(PriceResponse)
	err := c.cc.Invoke(ctx, "/price.pricer/GetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricerServer is the server API for Pricer service.
type PricerServer interface {
	GetPrice(context.Context, *PriceRequest) (*PriceResponse, error)
}

// UnimplementedPricerServer can be embedded to have forward compatible implementations.
type UnimplementedPricerServer struct {
}

func (*UnimplementedPricerServer) GetPrice(ctx context.Context, req *PriceRequest) (*PriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}

func RegisterPricerServer(s *grpc.Server, srv PricerServer) {
	s.RegisterService(&_Pricer_serviceDesc, srv)
}

func _Pricer_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricerServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/price.pricer/GetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricerServer).GetPrice(ctx, req.(*PriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pricer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "price.pricer",
	HandlerType: (*PricerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrice",
			Handler:    _Pricer_GetPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pricing/priceProtos/price.proto",
}
